import { h } from 'vue'
import {
  PhAppleLogo,
  PhArrowsDownUp,
  PhBarcode,
  PhCamera,
  PhCaretDown,
  PhCaretLeft,
  PhCaretRight,
  PhCaretUp,
  PhChartDonut,
  PhCheck,
  PhCheckCircle,
  PhClockCounterClockwise,
  PhCloud,
  PhCloudArrowUp,
  PhCrosshair,
  PhCube,
  PhDrop,
  PhEye,
  PhEyeSlash,
  PhFactory,
  PhFlask,
  PhGear,
  PhGrains,
  PhHandshake,
  PhHeart,
  PhImage,
  PhImageBroken,
  PhImages,
  PhInfo,
  PhLeaf,
  PhListChecks,
  PhMagnifyingGlass,
  PhMapPin,
  PhPlant,
  PhPlus,
  PhQuestion,
  PhReceipt,
  PhScales,
  PhScan,
  PhShoppingCart,
  PhSignOut,
  PhTag,
  PhTrash,
  PhUserCircle,
  PhWarning,
  PhWarningCircle,
  PhX
} from '@phosphor-icons/vue'

const icons = {
  'mdi-alert-circle': PhWarningCircle,
  'mdi-alert-circle-outline': PhWarningCircle,
  'mdi-alert-outline': PhWarning,
  'mdi-barcode-scan': PhBarcode,
  'mdi-camera': PhCamera,
  'mdi-cart-outline': PhShoppingCart,
  'mdi-chart-donut': PhChartDonut,
  'mdi-check': PhCheck,
  'mdi-check-circle': PhCheckCircle,
  'mdi-check-circle-outline': PhCheckCircle,
  'mdi-chevron-down': PhCaretDown,
  'mdi-chevron-left': PhCaretLeft,
  'mdi-chevron-right': PhCaretRight,
  'mdi-chevron-up': PhCaretUp,
  'mdi-close': PhX,
  'mdi-cloud-upload-outline': PhCloudArrowUp,
  'mdi-cog-outline': PhGear,
  'mdi-crosshairs-gps': PhCrosshair,
  'mdi-cube-outline': PhCube,
  'mdi-delete-outline': PhTrash,
  'mdi-eye-off-outline': PhEyeSlash,
  'mdi-eye-outline': PhEye,
  'mdi-factory': PhFactory,
  'mdi-flask-outline': PhFlask,
  'mdi-food-apple-outline': PhAppleLogo,
  'mdi-handshake-outline': PhHandshake,
  'mdi-heart': PhHeart,
  'mdi-heart-outline': PhHeart,
  'mdi-help-circle': PhQuestion,
  'mdi-help-circle-outline': PhQuestion,
  'mdi-history': PhClockCounterClockwise,
  'mdi-image': PhImage,
  'mdi-image-off-outline': PhImageBroken,
  'mdi-image-outline': PhImage,
  'mdi-image-plus': PhImages,
  'mdi-information-outline': PhInfo,
  'mdi-label-outline': PhTag,
  'mdi-leaf': PhLeaf,
  'mdi-line-scan': PhScan,
  'mdi-logout': PhSignOut,
  'mdi-magnify': PhMagnifyingGlass,
  'mdi-menu-down': PhCaretDown,
  'mdi-menu-right': PhCaretRight,
  'mdi-arrow-down': PhCaretDown,
  'mdi-arrow-up': PhCaretUp,
  'mdi-arrow-left': PhCaretLeft,
  'mdi-arrow-right': PhCaretRight,
  'mdi-close-circle': PhX,
  'mdi-information': PhInfo,
  'mdi-map-marker-outline': PhMapPin,
  'mdi-molecule-co2': PhCloud,
  'mdi-playlist-edit': PhListChecks,
  'mdi-plus': PhPlus,
  'mdi-receipt-text-outline': PhReceipt,
  'mdi-shaker-outline': PhGrains,
  'mdi-sprout-outline': PhPlant,
  'mdi-swap-vertical': PhArrowsDownUp,
  'mdi-text-box-search-outline': PhMagnifyingGlass,
  'mdi-account-circle-outline': PhUserCircle,
  'mdi-water-outline': PhDrop,
  'mdi-weight': PhScales
}

export const phosphor = {
  component: (props) => h(icons[props.icon] || PhQuestion, {
    size: '1em',
    weight: 'regular'
  })
}
